### ISSUE TITLE
如何continue training

### ISSUE THREAD

**Issue by Orange-rightperson** [yyliu01/RPL#10]
我注意到engine.py中包含了继续训练的parser,但是我怎么使用它呢

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

engine的代码是从这个[repository](https://github.com/charlesCXK/TorchSemiSeg)里面拿的, 我自己也没有用过, 所以continue training的话您可能得自己写一下。

Cheers,
Yuyuan

**Comment by Orange-rightperson** [comment]
好的好的，还有个问题是我使用单机双卡训练时会卡在一个epoch的最后一个batch，您知道这种问题怎么解决吗

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

很抱歉 我也没遇到过这个问题。我在这个[issue](https://github.com/yyliu01/RPL/issues/2)里跑了用4卡ddp的版本, 没有遇到您的情况。请问您用的是带contrastive learning的版本吗?

Cheers,
Yuyuan

**Comment by Orange-rightperson** [comment]
@yyliu01 好的，那您是怎么配置分布式训练的呢，相对应的代码调整能告诉我吗

**Comment by Orange-rightperson** [comment]
@yyliu01 同时让人费解的是我并不是程序报错，而是程序进行到最后一个batch的时候停止不动，既不报错也不继续

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

这个代码是可以进行分布式训练的, 在这个[issue](https://github.com/yyliu01/RPL/issues/2)里, 我有上传我的训练log [test_4gpus.txt](https://github.com/yyliu01/RPL/files/12830390/test_4gpus.txt)。

请问您双卡用的batch是多少? 跑的是有CoroCL的还是单纯RPL的版本?

**Comment by Orange-rightperson** [comment]
@yyliu01 
epoch=3, iter=[368/371] | entropy: 0.052 energy: 0.141, contrastive: 2.933
epoch=3, iter=[369/371] | entropy: 0.044 energy: 0.146, contrastive: 2.813
epoch=3, iter=[370/371] | entropy: 0.025 energy: 0.165, contrastive: 3.696
XXX lineno: 248, opcode: 164
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gyang/Codes/RPL/rpl_corocl.code/main.py", line 2, in <module>
    import torch.optim
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/site-packages/torch/__init__.py", line 721, in <module>
    _C._initExtension(manager_path())
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/site-packages/torch/cuda/__init__.py", line 759, in <module>
    from . import amp
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/site-packages/torch/cuda/amp/__init__.py", line 1, in <module>
    from .autocast_mode import autocast, custom_fwd, custom_bwd  # noqa: F401
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 5, in <module>
    import numpy as np
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/site-packages/numpy/core/__init__.py", line 101, in <module>
    from . import _internal
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/site-packages/numpy/core/_internal.py", line 146, in <module>
    format_re = re.compile(r'(?P<order1>[<>|=]?)'
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/sre_parse.py", line 948, in parse
    name = source.getuntil(">", "group name")
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/sre_parse.py", line 271, in getuntil
    self.__next()
  File "/home/gyang/anaconda3/envs/rpl/lib/python3.8/sre_parse.py", line 248, in __next
    self.next = char
SystemError: unknown opcode

这是其中一次报错，其他情况都是不会报错的，同时可以看到是运行到epoch3的最后一个batch才报错

**Comment by Orange-rightperson** [comment]
@yyliu01 
使用batchsize=4，跑的是CoroCL版本

**Comment by yyliu01** [comment]
@Orange-rightperson 请问pytorch的版本和各种dependency您是不是follow的这个[page](https://github.com/yyliu01/RPL/blob/main/docs/installation.md)? 还有原本图像的resolution有没有变化?

**Comment by Orange-rightperson** [comment]
@yyliu01 环境的准备完全按照指引，图像分辨率没有更改

**Comment by Orange-rightperson** [comment]
@yyliu01 仅仅更改了config文件中的batch_size以及main文件中的args参数的gpus

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

不好意思 我不能复现你的错误。我在这边用双卡跑了你的setup几个epoch, 还是没有任何问题。。。 

您可能需要先试试原本不加corocl的版本(rpl.code)会不会多卡出现问题。如果没有的话, corocl的版本可能需要检查一下[这个位置](https://github.com/yyliu01/RPL/blob/0d3c0b34802a92e9c4a2cd90082d31dca2f1f40b/rpl_corocl.code/engine/trainer.py#L50), 有些时候可能一个gpu有ood而另一个没有有可能会导致无法预料的问题, 虽然在我这边已经全部解决了。。。

**Comment by Orange-rightperson** [comment]
好的谢谢您
